version: '3.9'
services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
     - ./mosquitto.config:/mosquitto/config/mosquitto.conf
    networks:
     - chat
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=mqttchatuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mqttchat
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - backend
  blobstorage:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mqttchatuser
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mqttchat
    networks:
      - backend
    ports:
      - 27017:27017
    volumes:
      - blobstorage-data:/data/db
  dbcache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - dbcache-data:/data
    environment:
      - REDIS_PASSWORD=password
networks:
  chat:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  database-data:
  blobstorage-data:
  dbcache-data: