version: '3.9'
services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
     - ./mosquitto.config:/mosquitto/config/mosquitto.conf
    networks:
     - chat
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=mqttchatuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mqttchat
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  chat:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  database-data: